CREATE TABLE `gastos_varios` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` varchar(150) DEFAULT NULL,
  `CANTIDAD` int(11) DEFAULT NULL,
  `FECHA` datetime DEFAULT NULL,
  `CUENTA` int(11) DEFAULT NULL,
  `USUARIO` int(11) DEFAULT NULL,
  `ID_PRODUCTO` int(11) DEFAULT NULL,
  `TOTAL` decimal(8,2) DEFAULT NULL,
  `PRECIO` decimal(8,2) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_GASTOS_USUARIO_idx` (`USUARIO`),
  KEY `FK_GASTOS_CUENTA_idx` (`CUENTA`),
  KEY `FK_GASTOS_PRODUCTO_idx` (`ID_PRODUCTO`),
  CONSTRAINT `FK_GASTOS_CUENTA` FOREIGN KEY (`CUENTA`) REFERENCES `cuenta` (`IdCuenta`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_GASTOS_PRODUCTO` FOREIGN KEY (`ID_PRODUCTO`) REFERENCES `producto` (`IdProducto`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_GASTOS_USUARIO` FOREIGN KEY (`USUARIO`) REFERENCES `empleado` (`IdEmpleado`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


	
CREATE TABLE `db_casita`.`transferencia` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` VARCHAR(150) NULL,
  `FECHA` DATETIME NULL,
  `USUARIO` INT NULL,
  `CUENTA_ORIGEN` INT NULL,
  `CUENTA_DESTINO` INT NULL,
  `CANTIDAD` DECIMAL(8,2) NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_TRANFS_CUENTA_ORIGEN_idx` (`CUENTA_ORIGEN` ASC),
  INDEX `FK_TRANFS_CUENTA_DESTINO_idx` (`CUENTA_DESTINO` ASC),
  INDEX `FK_TRANFS_USUARIO_idx` (`USUARIO` ASC),
  CONSTRAINT `FK_TRANFS_CUENTA_ORIGEN`
    FOREIGN KEY (`CUENTA_ORIGEN`)
    REFERENCES `db_casita`.`cuenta` (`IdCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_TRANFS_CUENTA_DESTINO`
    FOREIGN KEY (`CUENTA_DESTINO`)
    REFERENCES `db_casita`.`cuenta` (`IdCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_TRANFS_USUARIO`
    FOREIGN KEY (`USUARIO`)
    REFERENCES `db_casita`.`empleado` (`IdEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

	
ALTER TABLE `db_casita`.`compra` 
ADD COLUMN `cuenta` INT NULL AFTER `Estado`,
ADD INDEX `FK_COMPRA_CUENTA_idx` (`cuenta` ASC);
ALTER TABLE `db_casita`.`compra` 
ADD CONSTRAINT `FK_COMPRA_CUENTA`
  FOREIGN KEY (`cuenta`)
  REFERENCES `db_casita`.`cuenta` (`IdCuenta`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

  
ALTER TABLE `db_casita`.`venta` 
ADD COLUMN `cuenta` INT NULL AFTER `Estado`,
ADD INDEX `FK_VENTA_CUENTA_idx` (`cuenta` ASC);
ALTER TABLE `db_casita`.`venta` 
ADD CONSTRAINT `FK_VENTA_CUENTA`
  FOREIGN KEY (`cuenta`)
  REFERENCES `db_casita`.`cuenta` (`IdCuenta`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  