CREATE TABLE `db_casita`.`gastos_varios` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` VARCHAR(150) NULL,
  `CANTIDAD` INT NULL,
  `FECHA` DATE NULL,
  `CUENTA` INT NULL,
  `USUARIO` INT NULL,
  `ID_PRODUCTO` INT NULL,
  `TOTAL` DECIMAL(8,2) NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_GASTOS_USUARIO_idx` (`USUARIO` ASC),
  INDEX `FK_GASTOS_CUENTA_idx` (`CUENTA` ASC),
  INDEX `FK_GASTOS_PRODUCTO_idx` (`ID_PRODUCTO` ASC),
  CONSTRAINT `FK_GASTOS_USUARIO`
    FOREIGN KEY (`USUARIO`)
    REFERENCES `db_casita`.`empleado` (`IdEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_GASTOS_CUENTA`
    FOREIGN KEY (`CUENTA`)
    REFERENCES `db_casita`.`cuenta` (`IdCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_GASTOS_PRODUCTO`
    FOREIGN KEY (`ID_PRODUCTO`)
    REFERENCES `db_casita`.`producto` (`IdProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

	
CREATE TABLE `db_casita`.`transferencia` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` VARCHAR(150) NULL,
  `FECHA` DATE NULL,
  `USUARIO` INT NULL,
  `CUENTA_ORIGEN` INT NULL,
  `CUENTA_DESTINO` INT NULL,
  `CANTIDAD` DECIMAL(8,2) NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_TRANFS_CUENTA_ORIGEN_idx` (`CUENTA_ORIGEN` ASC),
  INDEX `FK_TRANFS_CUENTA_DESTINO_idx` (`CUENTA_DESTINO` ASC),
  INDEX `FK_TRANFS_USUARIO_idx` (`USUARIO` ASC),
  CONSTRAINT `FK_TRANFS_CUENTA_ORIGEN`
    FOREIGN KEY (`CUENTA_ORIGEN`)
    REFERENCES `db_casita`.`cuenta` (`IdCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_TRANFS_CUENTA_DESTINO`
    FOREIGN KEY (`CUENTA_DESTINO`)
    REFERENCES `db_casita`.`cuenta` (`IdCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_TRANFS_USUARIO`
    FOREIGN KEY (`USUARIO`)
    REFERENCES `db_casita`.`empleado` (`IdEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

	
ALTER TABLE `db_casita`.`compra` 
ADD COLUMN `cuenta` INT NULL AFTER `Estado`,
ADD INDEX `FK_COMPRA_CUENTA_idx` (`cuenta` ASC);
ALTER TABLE `db_casita`.`compra` 
ADD CONSTRAINT `FK_COMPRA_CUENTA`
  FOREIGN KEY (`cuenta`)
  REFERENCES `db_casita`.`cuenta` (`IdCuenta`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

  
ALTER TABLE `db_casita`.`venta` 
ADD COLUMN `cuenta` INT NULL AFTER `Estado`,
ADD INDEX `FK_VENTA_CUENTA_idx` (`cuenta` ASC);
ALTER TABLE `db_casita`.`venta` 
ADD CONSTRAINT `FK_VENTA_CUENTA`
  FOREIGN KEY (`cuenta`)
  REFERENCES `db_casita`.`cuenta` (`IdCuenta`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
