/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Conexion.HibernateUtil;
import Entidad.ClsEntidadCuenta;
import Entidad.ClsEntidadOperacionHib;
import daos.impl.OperacionDaoImpl;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;

/**
 *
 * @author Alan
 */
public class FrmOperaciones extends javax.swing.JInternalFrame {

    List<ClsEntidadOperacionHib> operaciones;
    List<ClsEntidadCuenta> cuentas;
    OperacionDaoImpl operacionDao = new OperacionDaoImpl();
    
    /**
     * Creates new form FrmOperaciones
     */
    public FrmOperaciones() {
        initComponents();
        
        cargaOperaciones();
        actualizaTabla();
        
        cargarCuentas();
        actualizaComboCuentas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dateInicio = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        dateFin = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        cboCuentas = new javax.swing.JComboBox();
        btnFiltrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCuentas = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Operaciones");
        setPreferredSize(new java.awt.Dimension(707, 408));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros"));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Rango de Fecha:");
        jPanel1.add(jLabel1);
        jPanel1.add(dateInicio);

        jLabel2.setText("al:");
        jPanel1.add(jLabel2);
        jPanel1.add(dateFin);

        jLabel3.setText("Selecciona una cuenta para mostrar:");
        jPanel1.add(jLabel3);

        cboCuentas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cboCuentas);

        btnFiltrar.setText("Filtar");
        btnFiltrar.setPreferredSize(new java.awt.Dimension(57, 35));
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnFiltrar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.BorderLayout());

        tblCuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCuentas);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        // TODO add your handling code here:
        
        ClsEntidadCuenta cuenta = null;
        if(this.cboCuentas.getSelectedIndex() > 0){
            cuenta = this.cuentas.get( this.cboCuentas.getSelectedIndex() - 1 );
        }
        
        this.operaciones = this.operacionDao.listByFilters(
                dateInicio.getDate(),
                dateFin.getDate(),
                cuenta
        );
        
        this.actualizaTabla();
        
    }//GEN-LAST:event_btnFiltrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JComboBox cboCuentas;
    private com.toedter.calendar.JDateChooser dateFin;
    private com.toedter.calendar.JDateChooser dateInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCuentas;
    // End of variables declaration//GEN-END:variables

    private void cargaOperaciones() {
        
        this.operaciones = operacionDao.listAllOperaciones();
        
    }

    private void actualizaTabla() {
        
        DefaultTableModel modelo = new DefaultTableModel();
        
        String titulos[] = {"Cuenta", "Tipo", "Cantidad", "Monto Inicial", "Monto Final", "Usuario", "Fecha y Hora"};
        modelo.setColumnIdentifiers(titulos);
        
        for(ClsEntidadOperacionHib operacion : this.operaciones){
            String[] datos = new String[titulos.length];
            
            datos[0]=operacion.getCuenta().getNombre();
            datos[1]=operacion.getTipo();
            datos[2]=operacion.getCantidad().toString();
            datos[3]=operacion.getMontoInicial().toString();
            datos[4]=operacion.getMontoFinal().toString();
            datos[5]=operacion.getUsuario().getNombre();
            datos[6]=operacion.getHora().toString();
            
            modelo.addRow(datos);
            
        }
        
        this.tblCuentas.setModel(modelo);
        
    }

    private void cargarCuentas() {
        Session session = HibernateUtil.getInstance().getSession();
        session.beginTransaction();
        //session.delete(cuenta);
        
        this.cuentas = session.createQuery("FROM ClsEntidadCuenta").list();
        
        //session.getTransaction().commit();
        session.close();
    }

    private void actualizaComboCuentas() {
        Session session = HibernateUtil.getInstance().getSession();
        session.beginTransaction();
        
        this.cuentas = session.createQuery("from ClsEntidadCuenta").list();
        
        if(this.cuentas.size()<= 0){
            return;
        }
        
        int i=0;
        //int cuentaDefault = 0;
        String etiquetas[] = new String[cuentas.size()+1];
        etiquetas[i++] = "Todas las Cuentas";
        for(ClsEntidadCuenta cuenta: this.cuentas){
            etiquetas[i] = cuenta.getNombre();
            //if(cuenta.getCuentaDefault()){
            //    cuentaDefault = i;
            //}
            i++;
        }
        
        cboCuentas.setModel(new javax.swing.DefaultComboBoxModel(etiquetas));
        //cboCuentas.setSelectedIndex(cuentaDefault);
        
        session.close();
        
    }
}
